### ISSUE TITLE
Document intended usage for disabled Text

### ISSUE THREAD

**Issue by duranmla** [freenowtech/wave#103]
Relates to #96

**Comment by rafael-sepeda** [comment]
In order to make more clear the purpose of the disabled text color in addition to providing a descrition for this color slot I propose also to:
1. Rename `weak` to `secondary`. Word **weak** might be confused with **disabled**. Also **secondary** is more-or-less a standard name for this color slot.
2. Change `$color.text.disabled` to `$colors.brand.authenticBlue.200`. Currently it is set to 350 and it has not enough contrast/difference with `secondary` (`weak`) . We use actually already use `$colors.brand.authenticBlue.200` in disabled states in inputs, and buttons, checkbox and other. `$colors.brand.authenticBlue.350` it used for for `disable-inverted` states in some form controls, text input placeholder and default Tab in the tab bar. And this clashes with the idea of disabled.
3. Give name to the default text color - `primary`.
4. Describe all the color text slots.

So to be more systematic we can define the purpose of the text color slot this way:
* `primary` - color for most interface text whether body or headlines.
* `secondary` - for supplemental information with diminished contrast (often, the “gray text”). Like form microcopy, captions,  helper text and other medium emphasised text elements.
* `disabled` - for text in blocks, form elements or other components that are not available to a user at the moment (due to either permissions, dependencies, or pre-requisites) and need to feature  “incidental” states.

Regarding color contrast [WCAG 2.0 clearly defines that "incidental" text](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) that is not required to meet the contrast requirements.

**Comment by rafael-sepeda** [comment]
As and alternative instead of `primary` we can use `default`.

**Comment by rafael-sepeda** [comment]
This issue/discussion is also, probably, related to #97

**Comment by rafael-sepeda** [comment]
@agonzalezUX any comments from your side?

**Comment by rafael-sepeda** [comment]
@duranmla , @nlopin so then, what will be the next steps for this topic?

**Comment by duranmla** [comment]
We need to execute, sorry for the delays.
