### ISSUE TITLE
Ability to show icons within inputs

### ISSUE THREAD

**Issue by chrisrolfe198** [freenowtech/wave#143]
### Describe the feature you'd like
To display a copy icon within an input so that when it is clicked the contents is copied to the clipboard.

The documentation for the input says: "Icons: Sometimes inputs can include icons on the right. The icons can: Trigger a custom function (for example a date picker)". Does this mean it's already supported? If so can it be added to the documentation?

### Describe alternatives you've considered
Doing it manually separate from wave.

**Comment by snapsnapturtle** [comment]
Thanks for reporting this. Currently we don't have any guidelines or apis to allow setting an icon for an input. Could you share your use-case with us? :)

**Comment by rafael-sepeda** [comment]
@christopherrolfe198 this question is, probably, coming from this component?
https://monosnap.com/file/SSdOzeCVqAZDwyeBLPUYHaGCCDEGMC

We had a chat yesterday about it with **Amanda Espinosa**.

@snapsnapturtle regarding use-cases I can list some components that we have already in Wave that feature an clickable right/trailing icon:

- [view-icon to show/hide password - this is a dedicated component now](https://wave.free-now.com/components/password)
- [Chevron in dropdown](https://wave.free-now.com/components/Select)
- cross icon to clear the [SelectList component](https://wave.free-now.com/components/select-list). This is, basically, a standart feature for text inputs, but we, probably, do not have clear-action in our regular inputs?

If our new design library in Figma [we documented such an icon for a regular text input](https://www.figma.com/file/dTefUItBx5bfbxcCcMzMXm/Wave-DS?node-id=184%3A12).

Some libraries have this functionality in the core Text field components:
- [Material.io allows to setup Leading/Trailing icons in the basic input component](https://material.io/components/text-fields).
- [Orbit also supports Trailing icons](https://orbit.kiwi/components/inputfield/)

Would be good to have this also in our library. But I guess since we implemented the password component (that has a Trailing icon) separately having this functionality right away in the core Input component has some cons? Or not?

**Comment by christopherrolfe198** [comment]
So for me, there are a few issues here:

1. The documentation seems to indicate this feature is supported but it's not, at least not in a way that someone can add the component and add an icon with a custom function
2. We are working off of a design library in Figma that doesn't match the capabilities we have in the library which means when designs come through there is a guessing game of what exists and what doesn't which creates frustrations on the design and development side

**Comment by rafael-sepeda** [comment]
@christopherrolfe198 Most components in Figma are marked for now with "Not final". During the migration of the design library from Sketch to Figma I was checking the actual implementation (colors, spaces, etc.) but some things like this x-icon where existing in our library but never implemented (or hardcoded somewhere). The reason why I did not removed this feature from the new library because it was already in use in many places. In addition we do not have a dedicated `password` component in our library and we use the basic input component for it so we needed this functionality in it.

But I agree with you that we need to fix this.

**Comment by snapsnapturtle** [comment]
It sounds like this is a feature/improvement we should tackle (to match our documentation as well as the product requirements). I was doing some digging how other design systems achieve this and [this one](https://baseweb.design/components/input/) seemed to be the most suitable for our use-cases.

It works by providing a `startEnhancer` and an `endEnhancer`. For our system, we can probably start with the `endEnhancer`, which either accepts a render function or a `ReactNode`. That way, we can put icons there and link them to actions (like the eye icon in the password input to show/hide the plaintext version).

```ts
<Input endEnhancer={() => <CopyIcon size="small" />} />
```

**Comment by christopherrolfe198** [comment]
A related pattern raised by @duranmla in our PR in stash was around clickable icons for either side and might be worth covering here as well. It also fits the usecase for the password component. I.E. providing a specific interface/pattern for adding onclicks to icons, either through an additional button component that works out of the box with the enhancers or another way.

See screenshot
<img width="814" alt="Screenshot 2021-07-09 at 14 40 26" src="https://user-images.githubusercontent.com/2428612/125079181-9c45d980-e0c3-11eb-8194-34520ff3c0b7.png">

**Comment by arturmiglio** [comment]
We don't have this as a feature in any new specs, with Wave DS 2.0 (figma file).
