### ISSUE TITLE
Headline: make `size` a responsive property

### ISSUE THREAD

**Issue by nlopin** [freenowtech/wave#189]
In the design, we often have different font sizes defined for mobile and desktop versions of the UI. At the moment, there is no easy way to make it without explicit checks in the component. It would be great if we can provide a list or an object of sizes based on breakpoints to the `size` prop of the `Headline` component in a similar fashion we do with `p` and `m` props:

```jsx
<Headline as='h2' size={['m', 'l']}>Text</Headline>
<Headline as='h2' size={{_: 'l', small: 'm'}}>Text</Headline>
```

**Comment by rafael-sepeda** [comment]
@nlopin this would be great. We just need to document this in a clear way so everyone will understand how a particular Headline will look on different screens.

By design we do not have, for now, any definition on how a we transform headlines for mobile. Do you have on your side something already so we can bring this to the design group for discussion?

**Comment by nlopin** [comment]
As an example, the web registration's [thank you screen](https://www.figma.com/file/qYSaB23HCA6qQmAgbtuGbz/%F0%9F%93%90Credential-creation?node-id=0%3A1) uses different headline in different viewports

**Comment by rafael-sepeda** [comment]
@nlopin Ok, thanks. I will bring this to a discussion with other designers.

**Comment by snapsnapturtle** [comment]
relates to #55

**Comment by rafael-sepeda** [comment]
I will copy my question from #55 here (with a small correction, because I noticed a mistake 😅):

In code we have `fontSizes: ['0.75rem', '0.875rem', '1rem', '1.25rem', '1.5rem', '2rem', '2.5rem', '3rem']`,
and later

```
theme.fontSizes.small = theme.fontSizes[1];
theme.fontSizes.medium = theme.fontSizes[2];
theme.fontSizes.large = '1.125rem';
```

Did I get it right that we have?:

- x-small : 0.75rem
- small : 0.875rem
- medium : 1rem
- large : 1.25rem
- x-large : 1.5rem
- xx-large : 2rem
- xxx-large : 2.5rem
- xxxx-large : 3rem

If so, do we have an idea for how to improve the name for `xxx-large` and `xxxx-large`?

**Comment by rafael-sepeda** [comment]
@nlopin , @nlopin Here I made some explorations
https://www.figma.com/file/pTAzbj6iuSFFWTPKvmEJOA/Wave-setup?node-id=0%3A1

On the right side I also collected some examples for how others are managing the names for different text sizes. We can discuss this in a dedicated session.
