### ISSUE TITLE
Match semantic colors to Figma colors

### ISSUE THREAD

**Issue by martimalek** [freenowtech/wave#286]
### Describe the feature you'd like

There are some differences between the [semantic colors](https://github.com/freenowtech/wave/blob/main/src/essentials/Colors/Colors.ts#L35) in the code and the [Figma file](https://www.figma.com/file/dTefUItBx5bfbxcCcMzMXm/Wave-DS?node-id=11%3A3) that designers use.

The goal of this issue would be to add the missing colors in the code.

This is the part that we are missing:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/46452321/190660183-459348ce-7e0e-49b0-94ea-85bb243d8ac7.png">

### Describe alternatives you've considered

None.

**Comment by martimalek** [comment]
Reopening because we want to rethink how we want our semantic colors to look like. How broad/specific do we want them to be? (e.g. we have a `border.primary` but also a `forms.datepicker.calendar.borderHover`, do we really need the second one?)

**Comment by JanHamara** [comment]
**Action Items from meeting 01/12/2022:** 
- Plan / document approach with semantic colors
- Apply semantic colors to component styles config
   e.g.
   instead of `button.border.primary`: `Colors.something`
   utilize semantic: `button.border.primary`: `SemanticColors.border.secondary`

After these two are done, define an issue for setting up strategy for managing design system wide styling via theme, or CSS variables...
