### ISSUE TITLE
Need to clarify token usage/setup

### ISSUE THREAD

**Issue by rafael-sepeda** [freenowtech/wave#55]
We are setting up design tokens in Figma and in order to have 1-to-1 mapping with code (or close as possible) we need to clarify the definition of some tokens in code.

**Values** `rem` vs `px`
Should we use in tokens `rem` instead of `px`?

**fontSizes**
In code we have `fontSizes: ['0.75rem', '0.875rem', '1rem', '1.25rem', '1.5rem', '2rem', '2.5rem', '3rem'],`
and later 
- `theme.fontSizes.small = theme.fontSizes[1];`
- `theme.fontSizes.medium = theme.fontSizes[2];`
- `theme.fontSizes.large = '1.125rem';`

Did I get it right that we can consider:
- x-small : 0.75rem
- small : 0.875rem
- medium : 1rem
- large : 1.25rem
- x-large : 1.5rem
- xx-large : 2rem
- xxx-large : 2.5rem
- xxxx-large : 3rem

**Paragraph spacing**
How do we use spacing/margins for text?

**Spaces**
I'm not yet familiar with TypeScript, but if I get it right for Spaces we have a method that generates a list of possible values with `baseScale = 0.5` (8px) so at the end we get an array:
- 0 - 0rem, 0px
- 1 - 0.5rem, 8px
- 2 - 1rem, 16px
- 3 - 1.5rem, 24px
- 4 - 2rem, 32px
- 5 - 2.5rem, 40px
- 6 - 3rem, 48px
- 7 - 3.5rem, 56px
- 8 - 4rem, 64px
- 9 - 4.5rem, 72px
- 10 - 5rem, 80px

if so, how do we use `subSpaces = [0.25, 0.5, 0.75]` (0.4px, 8px, 12px) ? I mean, what name/token I should crate in Figma to map to `0.25` (0.4px) and `0.75` (12px)

**fontWeights**
We use only this values?:
- normal: 400,
- semibold: 600,
- bold: 700

**fonts**
Where do we use `monospace`?

**radii**
Did I get it right - this is **Border radius**?
If so - can we use for them **t-shirt sizes** naming convention that we use for **fontSizes**?
- none - 0rem
- small - 0.125rem (2px)
- medium - 0.25rem (4px)
- large - 0.5rem (8px)

**shadows**
We can rely on the [box-shadow definition](https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow)?:
`/* offset-x | offset-y | blur-radius | spread-radius | color */`

**Headline**
For the size of every headline (H1, H2, etc.) you're using `fontSizes` tokens:
- h1 - `font-size: ${get('fontSizes.7')};`
- h2 - `font-size: ${get('fontSizes.5')};`

So in order to keep consistency we should do the same?

**Comment by div-Leo** [comment]
Just to point out one discrepancy inside the library. 

This is what we currently have in the Wave documentation:
<img width="225" alt="Screenshot 2021-04-29 at 17 19 48" src="https://user-images.githubusercontent.com/12762609/116576115-8ff90f80-a90f-11eb-9a2b-9d8755ef6cf7.png">
Which in code for now corresponds to:
```js
<Text fontSize="2">
<Text fontSize="2">
<Text fontSize="2">
```

**Comment by div-Leo** [comment]
Just to point out one discrepancy inside the library. 

This is what we currently have in the Wave documentation:
<img width="225" alt="Screenshot 2021-04-29 at 17 19 48" src="https://user-images.githubusercontent.com/12762609/116576115-8ff90f80-a90f-11eb-9a2b-9d8755ef6cf7.png">
Which in code for now corresponds to:
```js
<Text fontSize="2"> // large 
<Text fontSize="1"> // medium
<Text fontSize="0"> // small
```
Also, give some other instructions from the design team large, medium, and small sizes of the label to the checkboxes are in order `1rem` `0.875rem` `0.75rem`.

The reason why we have `theme.fontSizes.large = '1.125rem';` in the code right now I think is due to that the Style System library we are using by default with the value `"large"` give `1.125rem` so I guess that is suppose to change.

**Comment by duranmla** [comment]
I will go point by point:
**Values:**
I will favor the usage of `rem` in this way the UI can adapt to user preferences. Nevertheless, there is a more longer conversation around the topic [here](https://stackoverflow.com/questions/11799236/should-i-use-px-or-rem-value-units-in-my-css)

**fontSizes:**
_I think you get it right_ But **do we need all of them?** do we actually use it? it seems to me overkill to have a `xxxx-large` (I even lost the count while typing the x)

In any case, we should try to come up with a set of aliases for the sizes and values because as @div-Leo already mentioned we have a bit of a discrepancy in different components.

**Can we just have:** x-small, small, medium, large, x-large ?

**Paragraph spacing:**
What do you mean on "How"? from my side I always try to replicate the design but I think there is no explicit rule like "paragraphs needs 1rem margin between them"

_Also there is a longer and deeper conversation about components should own the space inside not outside but there is other topic, just for you to be aware that IMHO a paragraph shouldn't have predetermined spaces that affect the surrounding_

**fontWeights:**
Sounds right to me only those three weights, do we need more?

**fonts:**
You mean like `monospace` code formatted? _I have never use a different font on any product_

**radii:**
We can make those aliases _(I think they are not defined)_

**shadows:**
we have this:

```
    {
        small: '0 0.0625rem 0.25rem 0 rgba(0,0,0,0.1)',
        medium: '0 0 1rem 0.1875rem rgba(0,0,0,0.08)',
        large: '0 0 0.75rem 0.25rem rgba(0,0,0,0.12)'
    }
```

Doesn't make sense for you?

**Headline**
🤔 This may help us to get the right aliases, nevertheless, it seems there are no good way out of the `xxx...` prefix. In that sense, `h1` -> `xxxxx-large`, `h2` -> `xxxx-large`, `h3` -> `xxx-large`, `h4` -> `xx-large`, `h5` -> `x-large`, `h6` -> `large` and `p` -> `medium`

Also maybe we can do `h1-large`, `hN-large`...

> Maybe we are taking too much subjects in a single thread and could lead to less efficiency on idea iteration?

**Comment by lukahartwig** [comment]
**Values**

My preference would be to stick with `rem`, mostly so we can adapt to user preference.

**fontSizes**

> Did I get it right that we can consider:
>
>    x-small : 0.75rem
>    small : 0.875rem
>    medium : 1rem
>    large : 1.25rem
>    x-large : 1.5rem
>    xx-large : 2rem
>    xxx-large : 2.5rem
>    xxxx-large : 3rem

Yes, that makes sense to me.

**Paragraph spacing**

If this means `line-height`, this is currently hard-coded for each headline, paragraph and so on. We don't have presets/tokens for this yet.

**Spaces**

`subSpaces` were meant as internal API and are not exposed. They are unused as far as I know so I wouldn't worry about this. We should probably removed them.

**fontWeights**

So far we only use those three yes.

**radii**

Also makes sense to me.

**shadows**

See @duranmla post with the current presets. Not sure if we could come up with a better naming there. Maybe make it related to `Elevation`? Like `flat`, `low`, `high`, `higher`?

**Headline**

It makes sense to use tokens to define `Headline`, but I also think it is important to not couple the tokens to the specific headlines. `xxxx-large` shouldn't automatically translate to `h1` for example, it should be an implementation detail.

**Comment by rafael-sepeda** [comment]
@lukahartwig , @duranmla 
By **Paragraph spacing** I mean space between Paragraphs:
https://monosnap.com/file/5weavnz5qEgseA6a1UXunXaqZ5vOzQ

For `subSpaces` we, probably, need a solution since we already use `0.75rem` (12px) in buttons and `0.25rem` (4px) as a spacer in some components (in code and in design).

**Comment by lukahartwig** [comment]
> @lukahartwig , @duranmla
> By Paragraph spacing I mean space between Paragraphs:
> monosnap.com/file/5weavnz5qEgseA6a1UXunXaqZ5vOzQ

Got it, we don't have any space between paragraphs by default. It is possible to use the values from `Spaces` on a case by case basis though.
